### ISSUE TITLE
Bhai Compound Interest ka Program in Progress

### ISSUE THREAD

**Issue by noshamedevil** [Mehulupase01/Hello-World#4]
Abhi time vagera nhi hai exam pe dhyan de and isko uda

**Comment by Mehulupase01** [comment]
Theek hai bhai exam pe dhyaan deta hoon waise bhi M3 kuch samaj nhi aarha hai @noshamedevil

**Comment by Mehulupase01** [comment]
Dude Exams khatam M3 fail total 4kt lekin apan chalu krte hai @noshamedevil
